name: ci
on:
  push:
    branches:
      - 'master'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: ghcr.io/trendyol/transporter
          tags: v1, latest
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          dockerfile: Dockerfile.ci
          name: Transporter
          run: echo ${{ steps.docker_build.outputs.digest }}
          addLatest: true
